### ISSUE TITLE
Able to rebroadcast a transaction that is already in the block chain

### ISSUE THREAD

**Issue by waldenraines** [unchained-capital/caravan#133]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

Caravan should not construct transactions that are not able to be broadcast.

## Current Behavior

I get these errors depending on the broken state of the spend:

```
There was an error broadcasting the transaction.: sendrawtransaction RPC error: {"code":-27,"message":"Transaction already in block chain"}
```

```
There was an error broadcasting the transaction.: sendrawtransaction RPC error: {"code":-25,"message":"Missing inputs"}
```

## Possible Solution

Check the transaction before it is broadcast to ensure everything is okay?

## Steps to Reproduce (for bugs)

1. Setup a funded wallet 
2. Self spend
3. Repeat step 2 and hope you see the error

Sorry these steps aren't better, I'm not entirely sure how I caused this.

## Environment

* Where are you running caravan:  localhost
* Operating system: Linux
* Browser and version: Chrome

```
caravan@0.2.0 /home/walden/code/caravan
├── unchained-bitcoin@0.0.13 
└─┬ unchained-wallets@0.0.12 
  └── unchained-bitcoin@0.0.12 

npm: 6.14.4 
node: v12.16.2
Linux 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64 GNU/Linux
```

**Comment by bucko13** [comment]
This should not be encountered anymore after #131, however note that if there is a bad (or no) connection with the blockchain, then the state of your inputs may not update properly. If this is the case, you should be seeing a warning after a broadcast to this effect, that also recommends refreshing the wallet. If the connection is completely down, then the state still won't be updated. If possible you should confirm that the inputs used in the tx are not spent and that that is reflected in the address table. 

Another situation where you might run into this is when using a private client. Make sure all of the latest addresses have been imported into the node so that Caravan can correctly reflect the state of your wallet's utxo set. 

Going to close as this should be clarified and easier to avoid after #131, but if anyone encounters something similar, please feel free to re-open.
