### ISSUE TITLE
Keep Zpub or Ypub in json config

### ISSUE THREAD

**Issue by mbican** [unchained-capital/caravan#136]
if I import Zpub it is immediately converted to xpub e.g.:
Zpub6xvDzwpKHczhpJzkkveFAqAsayzq7dC49Rr3R1qP8cGivqrMbUEip1fRbThiDLhtWA9EptBSVvUrKdrwwp7jt4bePNL3b7d9bo9EvgBQB4T
->
xpub68McGNk3RJMNh9T99Yc1vae4XFfg22XTzw9vvxn4zpgZCTezKkXKUmVDkLq4f6B9TQqeTLzChPPFRu24DC8m977mpDpo1tXBAck5Za3Vosz

If I later take the xpub from json and put it to electrum it doesn't work :-(

## I'm submitting a Bug report

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

as per slip-0132 https://github.com/satoshilabs/slips/blob/master/slip-0132.md based on script type extended public key should start with
P2SH: xpub
Multi-signature P2WSH in P2SH: Ypub
Multi-signature P2WSH: Zpub

I would want to convert to appropriate type *pub based address type

## Current Behavior

Currently regardless of address type extended public key is always converted to xpub.
It shows incorrect error message: "Your extended public key has been converted from Zpub to xpub, this may indicate an invalid network setting, if so correct setting, remove key and try again"

## Steps to Reproduce (for bugs)

1. go to https://unchained-capital.github.io/caravan/#/wallet
1. Swtich to P2WSH address type
1. Extended Public Key 1: "Enter as text"
1. paste: Zpub6xvDzwpKHczhpJzkkveFAqAsayzq7dC49Rr3R1qP8cGivqrMbUEip1fRbThiDLhtWA9EptBSVvUrKdrwwp7jt4bePNL3b7d9bo9EvgBQB4T

## Environment

* Where are you running caravan:  https://unchained-capital.github.io/caravan/#/wallet (v0.2.0)
* Operating system: Windows
* Browser and version: Brave Version 1.9.72 Chromium: 81.0.4044.138 (Official Build) (64-bit)

**Comment by bucko13** [comment]
Thanks for the report! I'm going to label this as a feature request rather than a bug as this is expected behavior given the feature support currently in Caravan. Basically, Caravan supports reading from the different xpub types to make it possible to import xpubs from trezor and electrum primarily, but then stays fully in the world of xpubs. Unfortunately, [BIP84](https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki)/[SLIP0132](https://github.com/satoshilabs/slips/blob/master/slip-0132.md) are not fully supported standards yet across all wallets and so Caravan for now has opted to keep extended public keys with the xpub/tpub prefixes while making sure to explicitly store the HD path in its config. Electrum won't know how to read this xpub, but you should be able to find tools that can convert the xpub from Caravan given the HD path into the zpub that Electrum understands. 

If you're interested in helping adding support for this, the first place I'd recommend looking is in the `unchained-bitcoin` library, specifically the tools used for converting xpub prefix versions [here](https://github.com/unchained-capital/unchained-bitcoin/blob/master/src/keys.js#L188)

**Comment by waldenraines** [comment]
See also https://github.com/unchained-capital/caravan/issues/218

**Comment by wksantiago** [comment]
Thanks 

> Thanks for the report! I'm going to label this as a feature request rather than a bug as this is expected behavior given the feature support currently in Caravan. Basically, Caravan supports reading from the different xpub types to make it possible to import xpubs from trezor and electrum primarily, but then stays fully in the world of xpubs. Unfortunately, [BIP84](https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki)/[SLIP0132](https://github.com/satoshilabs/slips/blob/master/slip-0132.md) are not fully supported standards yet across all wallets and so Caravan for now has opted to keep extended public keys with the xpub/tpub prefixes while making sure to explicitly store the HD path in its config. Electrum won't know how to read this xpub, but you should be able to find tools that can convert the xpub from Caravan given the HD path into the zpub that Electrum understands.
> 
> If you're interested in helping adding support for this, the first place I'd recommend looking is in the `unchained-bitcoin` library, specifically the tools used for converting xpub prefix versions [here](https://github.com/unchained-capital/unchained-bitcoin/blob/master/src/keys.js#L188)

Thanks @bucko13 for the information

**Comment by demerzel3** [comment]
You could use this tool https://jlopp.github.io/xpub-converter/ to convert the `xpub` back to `Zpub` for usage in other wallets.

**Comment by jevidon** [comment]
The Caravan Library is transitioning to a new home, and as part of this move current issues will be closed and archived. Please go check out the new location here: https://github.com/caravan-bitcoin/caravan/issues
