### ISSUE TITLE
Local Node rescan only finds first 20 addresses

### ISSUE THREAD

**Issue by destrys** [unchained-capital/caravan#142]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [x] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

When doing a rescan with a local bitcoind, I expect that all used addresses in the wallet will be found (at least if they were used sequentially and don't have gaps larger than the address gap limit). This is necessary to show the correct balance for the wallet.

## Current Behavior

It has been reported that only the first 20 addresses (and change addresses) are found:
https://twitter.com/dlawnroac/status/1269229613282201600
This means the wallet balance isn't correct. Additionally, I don't think the user is notified
that an additional rescan may be needed, leaving the unaware user in an incorrect state.

## Possible Solution

I haven't used it myself, but I read that `importmulti` now accepts multisig descriptors, and start-end indices for searching.
If that doesn't work, we could expand the import to at least a larger number (1000?).
And/or notify the user that that they may not have found all their used addresses.

## Steps to Reproduce (for bugs)

I didn't reproduce this one yet, but I suspect these are the steps:

1. Set up a wallet and use > 20 addresses.
2. Load that same wallet into a fresh caravan session.
3. Connect to a local bitcoind node and start a rescan.
4. When the rescan is complete, the balance will not be correct, and there won't be a notification that something may be incorrect.

## Environment

This was reported for a myNode user on June 6, 2020.

**Comment by bucko13** [comment]
Issue ACK. Tested out with a wallet on testnet with over 50 addresses used. 

While this is no means an acceptable long term solution, a temporary workaround that did work for me is to import + rescan multiple times. This is obviously faster on testnet and a relatively heavy lift on mainnet, but at least the wallet balance will show correctly eventually. 

`importmulti` with descriptors seems like a really great long term solution. There are plans for adding descriptor support into [unchained-bitcoin](https://github.com/unchained-capital/unchained-bitcoin/), so once that's available this should be an easy update to make.

**Comment by destrys** [comment]
So you would re-rescan until you saw a number of unused addresses (or you see the last address you remember using), right?

**Comment by bucko13** [comment]
Yep, exactly. You can also just keep doing it until you didn't see any new addresses via the lookahead. Since Caravan is following Core's 20 address lookahead policy and there's currently no way to customize this, it will keep updating on each new rescan until there are 20 addresses without any history or balance. If for some reason, a deposit was made to an address with a gap from the previously used address of 21+, then there is no way for Caravan to catch that. For example, if there was a deposit at path `*/0/40` and then the next one is at `*/0/70`, then it won't ever get imported. Sending to address `*/0/59` would bump that up though as a way to get around that particular situation.

**Comment by yunier2002** [comment]
I've seen this bug too but multiple imports/rescans hasn't worked for me. Another idea could be let user pick date/blocks ranges to rescan instead of full one that way takes less time with this command:

bitcoin-cli rescanblockchain 100000 120000

**Comment by jevidon** [comment]
The Caravan Library is transitioning to a new home, and as part of this move current issues will be closed and archived. Our engineers believe this issue is now resolve, if you are still experiencing this you are welcome to re-open the issue in the new location: https://github.com/caravan-bitcoin/caravan/issues
