### ISSUE TITLE
Connect to node over Tor

### ISSUE THREAD

**Issue by sahilc0** [unchained-capital/caravan#176]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [x] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior
Should be able to connect to node over Tor. This is useful not just because of **network level privacy, but also UX** - paste in link!

## Current Behavior
Cannot connect over Tor

## Possible Solution
For example - this is the Tor address you get from a node-in-a-box like Umbrel. I can plug this into wasabi and it should work fine. It would be great to have this with Caravan - even though it may not directly impact the Unchained Vault app.
![image](https://user-images.githubusercontent.com/8256062/92074324-a512a400-ed6a-11ea-9bb4-84716d9be96e.png)

**Comment by waldenraines** [comment]
I believe the solution here is to run caravan within the tor network and connect to your node using tor-browser (or equivalent setup).  

If you are running caravan outside of the tor network then you cannot connect it to a bitcoin full node within tor without using a proxy which [could dox you](https://news.ycombinator.com/item?id=23248154)

You may be able to accomplish this by doing the following (untested):

1. Clone the repository
1. `npm i`
1. ` npm run build`
1. Take the resultant build directory and host that within the tor network (potentially even on the same machine that runs your node)
1. Point caravan at your tor node

I believe [MyNode](https://mynodebtc.com/) does this out of the box.  The reason you can connect wasabi out of the box is because it also runs on the tor network.  Since caravan is just a set of static html files it doesn't have this ability.  

Something else to consider, since caravan is stateless, is to use something like [OnionShare](https://github.com/micahflee/onionshare/wiki) to host caravan.  Again I haven't personally tested this but in theory it should work.

I am closing this issue because there is nothing we can do on our end.
