### ISSUE TITLE
MultiSig on TestNet

### ISSUE THREAD

**Issue by JeremyNau** [unchained-capital/caravan#204]
## I'm submitting a…

* [ ] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [x] Support request

## Expected Behavior

I was wondering if Caravan supports the creation of TestNet MultiSig wallets and addresses. If so, is there documentation to approach?

## Current Behavior

1) Single Address: It looks like the tool would not recognize a test address I created using Electrum.
![image](https://user-images.githubusercontent.com/55710632/103486481-1616a680-4db3-11eb-933c-e58fdf7e7556.png)

2) Wallet: It looks like the tool WOULD recognized and convert my Vpub

![image](https://user-images.githubusercontent.com/55710632/103486545-68f05e00-4db3-11eb-8cf4-858b865454b9.png)

But not sure it would create a full testNet Multisig Wallet.

* Where are you running caravan:  https://unchained-capital.github.io/caravan/#/wallet
* Operating system: Windows
* Browser and version: Brave

Any context and details would be much appreciated!

**Comment by bucko13** [comment]
Hey Jeremy, 

Yes, testnet is supported but please note that it looks like you're pasting in a testnet bech32 _address_ in a field that is expecting a _public key_. There is no way to create a tool that can decompose an address into its constituent parts since the way that multisig addresses are created is by hashing the relevant script, which is a one-way process (i.e. it cannot be reversed). Incidentally, this gives multisig addresses more privacy before they are spent (but it also means it's your responsibility to backup the script which is required for spending. 

All that to say, the wallet view supports tpub which is a testnet extended public key (aka xpub) and the single address view supports generating testnet addresses from a set of public keys, but there is no way for Caravan to do anything with a testnet address (except spend to it).

**Comment by waldenraines** [comment]
I'm closing this per @bucko13's comment above.
