### ISSUE TITLE
 The path of caravan p2sh multi-signature is inconsistent with the path in the xpub file exported by ColdCard. 

### ISSUE THREAD

**Issue by caixiao-QA** [unchained-capital/caravan#212]
Network：Testnet
ColdCard Version：3.2.2
Caravan Version：v0.3.5

The path of caravan P2SH Multisig is inconsistent with the path in the xpub file exported by ColdCard. did caravan use a non-standard path?

**ColdCard P2SH path is "m/45'"，and xpub file content：**

```
{
  "p2sh_deriv": "m/45'",
  "p2sh": "tpubD8sGsX8cpVReqMzjTH9QxbSrQd5sTodLWpNf7HWNaJgUFH31LZQfgqxYoj2infUf49NPtao85o9a2x3PNhQ2SmU8xGmDKZaBdiyck711mBk",
  "p2sh_p2wsh_deriv": "m/48'/1'/0'/1'",
  "p2sh_p2wsh": "Upub5SzABYKibXvQLzV7QjmTwEASKFT5kYQd6rC1khZRsTDXakFN7npFgrdoiStpBd9tt3cWbEUX1JrPZ2TzgibzzGgvfqLHkJ5TyCCAsft4XRG",
  "p2wsh_deriv": "m/48'/1'/0'/2'",
  "p2wsh": "Vpub5mpRVCzdkDTtCwH9LrfiiPonePjP4CZSakA4wynC4zVBVAooaykiCzjUniYbLpWxoRotGiXwoKGcHC5kSxiJGX1Ybjf2ioNommVmCJg7AV2",
  "xfp": "5271C071"
}

```
**BUT caravan P2SH Multisig wallet path is "m/45'/1/0"，and Other Address Types（P2WSH and P2SH-P2WSH） are consistent**
![image](https://user-images.githubusercontent.com/37337093/106890399-3b853000-6724-11eb-99c7-6b5a8efc9020.png)

**Comment by bucko13** [comment]
I think "inconsistent" is maybe the wrong word to use here since the base paths are still actually the same (`m/45'`), it's just the derivation further down that is missing in the coldcard config, but they provide the required information necessary to derive the xpub at the path being shown in Caravan. The idea is that you do not want to be generating a "braid" (the term the code internally uses to refer to the set of xpubs used to generate a multisig wallet, so in this case a braid of three keys) from the path `m/45'` since that is the "purpose" index (see [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki)), but rather an index lower down. Since Coldcard is only giving the P2SH hardened derivation down to the purpose index, Caravan needs to use unhardened indexes for the other indexes (network and cosigner index respectively) to get the full path for the xpub that will be used in the braid. 

Hope that makes sense! I'm going to close this issue but if you have any further questions related to this, feel free to re-open.

**Comment by aaronisme** [comment]
@bucko13  I agree this issue title is not correct.  but I still think there is one issue or open question to discuss. if the multi-sig wallet generated on ColdCard is not the same as generated in the caravan. 

Take this for example. 
One user has two coldcard devices. if he/she generates a P2SH multi-sig wallet on coldcard, it will use m/45'/0/0 as the derivation path for the public key to generate the multi-sig wallet address. 

The same user use caravan to generate the multi-sig wallet using the same coldcard device. Cavan will use m/45'/0/0/0/0 as the derivation path to generate the multi-sig wallet address. 

So the address will be different. I think it will be an issue. and meanwhile, for P2SH-P2MS multi-sig wallet how do you think just following [BIP-45](https://github.com/bitcoin/bips/blob/master/bip-0045.mediawiki).

But currently, it seems there are not many wallet providers that follow the BIP-45.

Thanks

**Comment by bucko13** [comment]
First I'd just like to clarify a couple of terms. You said you think that "the multi-sig wallet generated on ColdCard is not the same as generated in the caravan." What you shared in the screenshot from Coldcard though is not a multisig wallet configuration, it is a file that coldcard provides for exporting its xpubs. This is the same as when you plug in a ledger or trezor as the other two device options and caravan will ask for xpubs and then derive xpubs at the desired paths from there. Coldcard can't have such direct interaction and so it provides a file that lets coordinators like Caravan derive what they need from it. After you create the wallet at this step, caravan will provide you with a wallet config file that can then be imported into your Coldcard. In our testing, there have been no compatibility issues in these steps and Coldcard happily recognizes the wallet file and signs for transactions it has ownership of keys over. If you've experienced otherwise though, then this is definitely a bug and we should absolutely investigate further.

I think what you're describing though is a problem or challenge in operating with all mutisig wallets. A user could generate a wallet using a braid that is at _any_ derivation path. The fact that the standards, as you point out, are not universally followed makes this even more difficult. Coldcard is only providing the xpub for hardened purpose index for P2SH, but you absolutely do not want to use that to generate your wallet. So a wallet coordinator (whether that's caravan, electrum, or any other) will have to make its own determination which standard to follow if any at all since the user can themselves enter a custom value for the paths too. 

Note that Caravan doesn't force you to use any path. It provides a sane default based on the way it's following the standards. It is 100% still recommended no matter which coordinator you use to keep a backup of the wallet configuration file since without the exact derivation path, the wallet cannot be recovered. In fact, the situation you're describing can be considered an ADVANTAGE in that you can use the same device/seed to generate braids for multiple wallets. This can be done for many reasons including privacy so that in the event that an xpub is leaked without the path, the attacker still wouldn't be able to identify spends because they don't know the path to generate the public keys from. 

To directly address your examples quickly:
> The same user use caravan to generate the multi-sig wallet using the same coldcard device. Cavan will use m/45'/0/0/0/0 as the derivation path to generate the multi-sig wallet address.

Based on your screenshot though, Caravan will not use that path but is defaulting to the path `m/45'/[1|0]/0` (`master/purpose[hardened]/coin_type/account`) which matches the example you shared for the path you got from Coldcard. If you want Caravan to create a multisig wallet config with a braid generated at that path though, you can and is supported by Caravan, I would just recommend you keep a backup if you're not using the default values.

My only follow-up question now is to clarify what the question or bug is you'd like to report. Do you think the default path should be different based on the standards? If so, if you have a suggestion for a different path, we'd be happy to entertain it and a PR. But I don't think we'd accept any PR that made the path default to the same that the xpub derivation path that is exported (`m/45'`). If not is there a bug that you're running into where you're unable to sign transactions or coordinate between the caravan wallet and the wallet imported into the coldcard? 

Based on this:
> So the address will be different. I think it will be an issue.
it sounds like maybe you're running into issues signing or generating addresses but I'm not really clear on what those might be? The Coldcard doesn't really generate addresses for you, it just confirms when you're signing that it is the owner of the public key in a quorum for a particular address and that it matches with the derivation path for the xpub imported from the wallet config. If you finish creating the wallet in Caravan and then add the wallet config (properly formatted for the Coldcard device) which will indicate the derivation path of `m/45'/1/0` then the Coldcard will be able to confirm that during signing. 

Sorry if this answer is a little long! I really want to make sure any confusion is cleared up though. Feel free to follow up if anything was clearly explained.

**Comment by aaronisme** [comment]
@bucko13 Thanks for your reply, really helpful.

First, I would like to apologize for this issue. the title and description may be lead to some misunderstanding here. and we have tested on Caravan with ColdCard, the transaction can be signed correctly. so this issue is not correct. I am sorry for that.

Second, my question is actually here:

> But I don't think we'd accept any PR that made the path default to the same that the xpub derivation path that is exported (m/45'). 

The reason for this is Caravan would like to follow BIP-44 for P2SH multi-sig? 

Thanks!

**Comment by bucko13** [comment]
Yes that's correct. To be clear, there are NO wallets that use that path for generating wallet keys as far as I know. All wallets, including with Coldcard, may use that as a root for deriving keys in a wallet further down the derivation path (e.g. `m/45'/0/0/0...`) but none I have encountered would put in a public key derived from `m/45'` directly.

**Comment by aaronisme** [comment]
> Yes that's correct. To be clear, there are NO wallets that use that path for generating wallet keys as far as I know. All wallets, including with Coldcard, may use that as a root for deriving keys in a wallet further down the derivation path (e.g. `m/45'/0/0/0...`) but none I have encountered would put in a public key derived from `m/45'` directly.

Seems ColdCard directly use  'm/45'' as the deriv path:
https://github.com/Coldcard/firmware/blob/d9d78b9ab1c9202db8ad0cb219cbc67d3b0ddddf/shared/multisig.py#L1408

**Comment by bucko13** [comment]
Interesting! Didn't realize they did that as I've only personally used coldcard myself indirectly via coordinators (like Caravan). I can't comment on their reasoning, but yeah it's neither following BIP-44 or BIP-45 (despite using that purpose index). 

In any case, this shouldn't be much of a problem except in so far as the defaults could get people stuck, but still recoverable. As long as you have a backup of your wallet config (and we want to support importing a wallet config directly from coldcard eventually too which will make it even easier to keep things compatible, see [this PR](https://github.com/unchained-capital/unchained-wallets/pull/44/files#diff-6759e0460bde0579a7ddab2ca74b4474036f4b8977cede4e4c019bb6e75a288aR629) for a draft of this effort) then there won't be any problems in terms of interoperability. While the default is not the same as what comes from the coldcard, you can change the default to be `m/45'` in caravan (see screenshot attached), or use the caravan's default for the key from the coldcard. The only thing you can't do of course is derive keys at hardened indexes further down, which is too bad, but not a huge concern.

<img width="836" alt="Screen Shot 2021-02-09 at 3 18 01 PM" src="https://user-images.githubusercontent.com/4344978/107429820-02650b00-6aea-11eb-958d-3770771317ff.png">

So to take it back to your example:
>One user has two coldcard devices. if he/she generates a P2SH multi-sig wallet on coldcard, it will use m/45'/0/0 as the derivation path for the public key to generate the multi-sig wallet address.
The same user use caravan to generate the multi-sig wallet using the same coldcard device. Cavan will use m/45'/0/0/0/0 as the derivation path to generate the multi-sig wallet address.

That's correct that if you just tried to generate wallets independently with caravan and coldcard using their defaults, they wouldn't match, but you could still recover the wallet generated from coldcard in Caravan (which is nice particularly if you want to use the seed in another device... like Cobo? 😁) as long as you're explicit about the derivation path. That's one reason we try and highlight the importance of the derivation path in the wallet creation process, to avoid the type of problem you're pointing out. 

And like I said, we very much intend to add better support for importing wallet configs from lots of sources (coldcard, electrum, cobo, etc.) so hopefully that makes things even easier.
