### ISSUE TITLE
Interact > Confirm Ownership > Text pasting option missing

### ISSUE THREAD

**Issue by sahilc0** [unchained-capital/caravan#26]
![image](https://user-images.githubusercontent.com/8256062/77377672-0997f480-6d31-11ea-953f-5ed5187f1c67.png)

Only showing HWW and Hermit. Should be option to paste text.

v0.1.5
Testnet
Brave Browser
MacOS

**Comment by sahilc0** [comment]
@bucko13 i could be wrong, but this is a bug not an enhancement. In a video demo, Dhruv shows that this was an existing feature. For some reason it’s not showing up.

**Comment by waldenraines** [comment]
This is fixed in the `address-importer` branch.

**Comment by bucko13** [comment]
@sahilc0 I think you might be thinking of the public key importing support for the option to paste text. That option should still be available in all public branches (see attached example screenshot). 

![gscreenshot_2020-04-10-112621](https://user-images.githubusercontent.com/4344978/79002915-1a10e300-7b17-11ea-8447-953c9128dbc1.png)

Confirming ownership is a different type of functionality that is more specifically targeted for hardware and hermit since they don't automatically expose their keys for security/privacy reasons. This function allows you to make a call to confirm that your device is an owner of one of the keys in a quorum. For plain text though you don't actually need this functionality since you should be looking at the key already and can use the eyeball test to confirm it's in the quorum. 

This could be a future enhancement to support the pasting of an xpub and a path and then cycle through a certain number of indexes to see if we can find a key that's in the quorum but currently that's not a feature that is supported.

**Comment by sahilc0** [comment]
I double checked the video and seems like  @bucko13 is correct, we should leave it as a feature enhancement. Thanks!

**Comment by jevidon** [comment]
The Caravan Library is transitioning to a [new home](https://github.com/caravan-bitcoin/caravan), and as part of this move all current issues will be closed and archived. If you're still interested in your feature request being addressed, you're welcome to reopen it at the new location: [https://github.com/caravan-bitcoin/caravan/issues](https://github.com/caravan-bitcoin/caravan/issues)
