### ISSUE TITLE
Caravan wallet shows 0 balance when explorer can see  the transaction

### ISSUE THREAD

**Issue by hium74** [unchained-capital/caravan#285]
## I'm submitting a…

* [ ] Support request

## Expected Behavior
I should be able to see the balance of the 2 transactions I made. Having used the first multisig address it should not be in the zero balance address, and the transactions visible.

## Current Behavior
I tested a caravan wallet using its first address. I sent 2 small transactions, yet the specific address is listed in the zero balance list. Though, when searching in the mem pool the address appears and shows the two transactions.
This seems a really absurdity to me, but I am a noob.
I'd like you to notice, although in my opinion should no matter, that this multisig wallet is under a node. In fact, when I load it to connect I have to enter the passowrd's node. I also find very weird this behaviour. Does it mean if I change the node or loose the password I will not be able to sign transaction (if the first problem is solved)

## Environment
Caravan wallet with private access

* Where are you running caravan: localhost
* Operating system: Raspberry mynode 3.0.9
* Browser and version: Mynode

 

<img width="1124" alt="Caravan wallet" src="https://user-images.githubusercontent.com/83580581/215663603-7827f2f0-e581-44b4-83e8-3a5ea229f0e3.png">
<img width="1399" alt="Meme pool" src="https://user-images.githubusercontent.com/83580581/215663628-5e4b7e66-6114-4f0e-8a7b-1006f98f5595.png">

**Comment by bucko13** [comment]
For some background, Caravan has two mechanisms for consensus, from the [main page](https://unchained-capital.github.io/caravan/#/help) of the caravan app:

> In order to look up wallet addresses and their balances, and broadcast transactions, Caravan requires knowledge of the constantly changing bitcoin network.

> Running a full bitcoin node is the most private way to determine the current state of the bitcoin network. Caravan can be easily configured to use your own node for consensus information and broadcasting transactions.

> If you don't want to or cannot run your own full node, Caravan defaults to using the freely available API at blockstream.info.

I suspect what's happening here is that you're connected to your own node but you haven't imported the addresses that are derived from your wallet configuration into your actual bitcoin node. If the addresses are not being watched then you're unable to query the balances for them. What makes this more complicated is that you can only know about balance changes _after_ your node starts watching them. So if you spent some test utxos, then imported your addresses to your node, then sent some more test utxos, you would only see the second test and not the first without doing a rescan. 

You can do a kind of test to confirm that this is probably what's going on by doing the public client option which uses blockstream.info rather than your own node. You lose the privacy of course but it will confirm that Caravan is at least capable of querying the correct balances. 

Alternatively you could import and then try again, but you won't have knowledge of the initial tests. 

You could also force your node to do a rescan of the blockchain after importing the addresses (this is made available after setting up the wallet), but note that this will make your node unavailable to other services too while it rescans the whole blockchain and reconstructs the current utxo set and history of your wallet.

**Comment by hium74** [comment]
Thank you so much for your answer!
Super weird stuff for a nooby.

Could you explain more in detail how to import addresses into the node? I pressed import addresses and rescan and vice versa then waited for a few hours but nothing changed.

I also have another big concern. It seems like I have no way to access it another way than through my node as it asks me for my node password. So is the account irremediably tied to the node? What if I dismiss the node?

**Comment by bucko13** [comment]
> Could you explain more in detail how to import addresses into the node? I pressed import addresses and rescan and vice versa then waited for a few hours but nothing changed.

A rescan triggers a rescan of the whole blockchain so depending on your hardware that can take more than a few hours. You can check on your device what the progress is. I believe mynode shows this in their dashboard somewhere. 

> I also have another big concern. It seems like I have no way to access it another way than through my node as it asks me for my node password. So is the account irremediably tied to the node? What if I dismiss the node?

When you first setup a wallet in caravan there is a field to enter the "client" you want to use to query the blockchain. This is where you can persist this information. It is then possible to export that as a configuration file that you can save and reuse. If you want to change this information you can either re-setup the wallet or edit the configuration file directly. 

![Screen Recording 2023-02-02 at 4 19 57 PM](https://user-images.githubusercontent.com/4344978/216462787-f2d844b0-8a1b-44c1-879c-9b6ae81b6009.gif)

**Comment by hium74** [comment]
Thank you very much for the info which was very useful.

I still cannot get the node to rescan. Would you tell me the steps in order to do so? WHen I click on rescan I cannot see anything happening

Thank you

**Comment by bucko13** [comment]
Caravan doesn't integrate much with your node at all, just getting info about addresses so finding out the state of a rescan (if you actually triggered the rescan) will be through your node's interface, not Caravan, so you'll have to check with whatever you're using. 

I'd recommend trying to connect to the public client if you can figure that out and don't mind the privacy hit and see that it's just a node issue and not a caravan issue.

**Comment by bucko13** [comment]
Closing this issue now assuming this has been resolved and not reported by anyone else. Feel free to open a new issue if you're still having problems.
