### ISSUE TITLE
github-pages fork successfully deploys but does not load

### ISSUE THREAD

**Issue by realBitcoinDog** [unchained-capital/caravan#337]
## I created a brand new caravan fork, but my github-pages fails to load. https://realbitcoindog.github.io/caravan

* [X] Regression (a behavior that used to work and stopped working in a new release)
* [ ] Bug report 
* [ ] Feature request
* [ ] Documentation issue or request
* [ ] Support request

## Expected Behavior

I made a brand new fork of github.com/unchained-capital/caravan, made no changes, and had my github-page auto deploy, but it fails to load.

This is is my github page: https://realbitcoindog.github.io/caravan/

![github-page_created](https://github.com/unchained-capital/caravan/assets/112731972/cee79447-936d-477e-9f70-51b02c486080)

My active deployment shows as successful: https://github.com/realBitcoinDog/caravan/deployments/
![Active_Deployment_Successful](https://github.com/unchained-capital/caravan/assets/112731972/266ee83b-4aef-4478-ad1e-007f899d143b)

The log shows no errors: https://github.com/realBitcoinDog/caravan/actions/runs/5909547310/job/16030253704
![log](https://github.com/unchained-capital/caravan/assets/112731972/721406c8-c40b-40b7-93f6-804d518341fa)

The workflow looks good: https://github.com/realBitcoinDog/caravan/actions/runs/5909547310
![workflow](https://github.com/unchained-capital/caravan/assets/112731972/d5df75a2-3792-4aec-9f17-ce3ccc586990)

If I look at the other pages of recent caravan forks, they look like they're working as intended for my Chrome browser on my Windows laptop:
https://github.com/unchained-capital/caravan/forks
https://abhishandy.github.io/caravan/#/
https://agentsm1th.github.io/caravan/#/

By the way I think it's cool that bucko13 has the updated site logo, and cool light blue color:
https://bucko13.github.io/caravan/#/

Can you please help update documentation if there's something else that must be done for github-pages to work from a brand new fork? Thanks!

## Steps to Reproduce (for bugs)

1. step 1
2. step 2
3. step 3
4. step 4

## Environment

* Where are you running caravan:  
* Operating system: 
* Browser and version:

**Comment by realBitcoinDog** [comment]
@bucko13 I want to compliment your page! You have the new site logo, and a light blue color. https://bucko13.github.io/caravan/#/

Maybe you know why a brand new fork isn't working to populate the github-pages?  It just shows as blank. Thanks!

**Comment by bucko13** [comment]
Hey @realBitcoinDog sorry to hear you're having trouble! Github pages is a little more confusing to setup for something like this since it's not a user or org page but a project page (see about gh page types [here](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites)). This makes things a little different to work out of the box. First, you'll want to make sure you're publishing from the right branch (gh-pages is what's configured from the script, not `master`). 
<img width="788" alt="Screenshot 2023-08-22 at 8 10 20 PM" src="https://github.com/unchained-capital/caravan/assets/4344978/b831d80e-055d-425d-b06c-1b088658855d">

Once you've got that set you should be able to deploy using the npm script: ` npm run gh-pages` . By default this will compile a build from the current state of your code and push to the `origin` remote repo setup in your local git project. You can target repos by another name like this: `npm run gh-pages -- -o my-remote`. Basically what's happening is that the site is being built and pushed to a "special" branch with the compiled site files as opposed to the raw code you see on master. If you look at the gh-pages branch on any of the sites you found are working you'll see what those look like. 

If you get it working and want to push up some updates to the readme, I'd be happy to help get that reviewed and approved asap!

**Comment by realBitcoinDog** [comment]
@bucko13 got it thank you!! 

https://realbitcoindog.github.io/caravan/#/

i had to re-fork the repo and uncheck the box that said "only copy master"

that's what let me get the gh-pages branch, and it all works! thanks!!

one day ill update the documentation for u to approve!
